# Generated by Django 4.0.4 on 2022-05-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.IntegerField()),
                ('team_member_names', models.CharField(max_length=510)),
            ],
        ),
    ]
